class SQL_CONST {

    // Estoque
    static SQL_ESTOQUE_FIND = "SELECT ID, IDEMPRESA, IDPRODUTO, QUANTIDADE FROM ESTOQUE WHERE IDPRODUTO = ?;";
    static SQL_ESTOQUE_INSERT = "INSERT INTO ESTOQUE (IDEMPRESA, IDPRODUTO, QUANTIDADE) VALUES (?, ?, ?) RETURNING ID;";
    static SQL_ESTOQUE_UPDATEQTD = 'UPDATE ESTOQUE SET QUANTIDADE = ? WHERE ID = ? RETURNING ID;'

    // Licenca
    static SQL_GET_LICENCA = 'SELECT FIRST 1 DATA_VENCIMENTO, DIAS_RESET FROM LAMMER_LIC ORDER BY CODIGO DESC;'
    static SQL_SET_LICENCA = 'UPDATE LAMMER_LIC SET DATA_ATIVACAO = ?, DIAS_RESET = ?, DATA_VENCIMENTO = ?, DATA_PAGAMENTO = ? WHERE 1 = 1';
    static SQL_GET_SBT = 'SELECT A.* FROM (SELECT FIRST 1 DATA_VENCIMENTO as CONFIG FROM LAMMER_LIC ORDER BY CODIGO DESC) A UNION SELECT SBT FROM CONFIG;'
    static SQL_GET_FORNECEDORES = 'SELECT ID, NOME FROM FORNECEDORES;'

    // Produto Aliquota
    static SQL_PRODUTO_ALIQUOTA_INSERT = "INSERT INTO PRODUTO_ALIQUOTA (IDPRODUTO, UF, CST, CFOP, ALIQUOTA, REDUCAO_BASE, ALIQUOTA_FECOEP) VALUES (?, ?, ?, ?, ? , ?, ?) RETURNING ID;";
    static SQL_PRODUTO_ALIQUOTA_FIND = "SELECT * FROM PRODUTO_ALIQUOTA WHERE IDPRODUTO = ?;";

}

class VARIABLE_CONST {
    static C_TOKEN_MASTER = '4y0h9WnLw'
}
module.exports = { SQL_CONST, VARIABLE_CONST }