class SQL_CONST {

    static SQL_ESTOQUE_FIND = "SELECT ID, IDEMPRESA, IDPRODUTO, QUANTIDADE FROM ESTOQUE WHERE IDPRODUTO = ?;";
    static SQL_ESTOQUE_INSERT = "INSERT INTO ESTOQUE (IDEMPRESA, IDPRODUTO, QUANTIDADE) VALUES (?, ?, ?) RETURNING ID;";
    static SQL_ESTOQUE_UPDATEQTD = 'UPDATE ESTOQUE SET QUANTIDADE = ? WHERE ID = ? RETURNING ID;'

}


module.exports = SQL_CONST